env:
  es6: true
  jest: true
  node: true
parserOptions:
  sourceType: 'module'
  ecmaVersion: 2018
extends: 
  - 'eslint:recommended'
  - 'airbnb-base'
rules:
  indent:
    - error
    - 2
  linebreak-style:
    - error
    - unix
  quotes:
    - error
    - single
  semi:
    - error
    - always
  no-var: "error"
  no-multiple-empty-lines: ["error", {max: 1, maxBOF: 0, maxEOF: 1}]
  no-eval: "error"
  no-nested-ternary: "error"
  no-tabs: "error"
  no-octal: "error"
  array-bracket-spacing: "error"
  no-trailing-spaces: "error"
  eol-last: "error"
  no-param-reassign: 0
  no-underscore-dangle: 0
  consistent-return: 0
  no-plusplus: 0
  func-names: 0
  camelcase: 0
  max-len: 0
  prefer-promise-reject-errors: 0
  no-use-before-define: 0
  no-throw-literal: 0
  global-require: 0
  radix: 0
  class-methods-use-this: 0
  no-console: 0
  prefer-destructuring: 0
  no-prototype-builtins: 0
  prefer-rest-params: 0
  import/no-dynamic-require: 0
  comma-dangle: ["error", "never"]
  arrow-parens: ["error", "as-needed"]
  object-curly-newline: 0
  arrow-body-style: 0
